import { BunWayApp, bunway as createBunway, type BunWayOptions } from "./core/app";
import { json, urlencoded, text, raw } from "./middleware/body-parser";
import { cors } from "./middleware/cors";
import { serveStatic } from "./middleware/static";
import { cookieParser } from "./middleware/cookie-parser";
import { compression } from "./middleware/compression";
import { helmet } from "./middleware/helmet";
import { rateLimit } from "./middleware/rate-limit";
import { csrf } from "./middleware/csrf";
import { session } from "./middleware/session";
import { logger } from "./middleware/logger";
import { upload } from "./middleware/upload";
import { timeout } from "./middleware/timeout";
import { hpp } from "./middleware/hpp";
import { validate } from "./middleware/validation";
import { sse } from "./middleware/sse";
import { responseTime } from "./middleware/response-time";
import { requestId } from "./middleware/request-id";
import { methodOverride } from "./middleware/method-override";
import { favicon } from "./middleware/favicon";
import { jwt, jwtSign, jwtDecode } from "./middleware/jwt";
import { passport, passportInitialize, passportSession, passportAuthenticate } from "./middleware/passport";
import { tokenVault, VaultMemoryStore } from "./middleware/token-vault";

interface BunwayFactory {
  (options?: BunWayOptions): BunWayApp;
  json: typeof json;
  urlencoded: typeof urlencoded;
  text: typeof text;
  raw: typeof raw;
  cors: typeof cors;
  static: typeof serveStatic;
  cookieParser: typeof cookieParser;
  compression: typeof compression;
  helmet: typeof helmet;
  rateLimit: typeof rateLimit;
  csrf: typeof csrf;
  session: typeof session;
  logger: typeof logger;
  upload: typeof upload;
  timeout: typeof timeout;
  hpp: typeof hpp;
  validate: typeof validate;
  sse: typeof sse;
  responseTime: typeof responseTime;
  requestId: typeof requestId;
  methodOverride: typeof methodOverride;
  favicon: typeof favicon;
  jwt: typeof jwt;
  passport: typeof passport;
  passportInitialize: typeof passportInitialize;
  passportSession: typeof passportSession;
  passportAuthenticate: typeof passportAuthenticate;
  tokenVault: typeof tokenVault;
}

const bunway = ((options?: BunWayOptions) => createBunway(options)) as BunwayFactory;

bunway.json = json;
bunway.urlencoded = urlencoded;
bunway.text = text;
bunway.raw = raw;
bunway.cors = cors;
bunway.static = serveStatic;
bunway.cookieParser = cookieParser;
bunway.compression = compression;
bunway.helmet = helmet;
bunway.rateLimit = rateLimit;
bunway.csrf = csrf;
bunway.session = session;
bunway.logger = logger;
bunway.upload = upload;
bunway.timeout = timeout;
bunway.hpp = hpp;
bunway.validate = validate;
bunway.sse = sse;
bunway.responseTime = responseTime;
bunway.requestId = requestId;
bunway.methodOverride = methodOverride;
bunway.favicon = favicon;
bunway.jwt = jwt;
bunway.passport = passport;
bunway.passportInitialize = passportInitialize;
bunway.passportSession = passportSession;
bunway.passportAuthenticate = passportAuthenticate;
bunway.tokenVault = tokenVault;

export default bunway;
export { bunway };

export { BunWayApp } from "./core/app";
export { Router } from "./core/router";
export { Route } from "./core/route";
export { BunRequest } from "./core/request";
export { BunResponse } from "./core/response";
export { HttpError, isHttpError } from "./core/errors";

export { json, urlencoded, text, raw } from "./middleware/body-parser";
export { cors } from "./middleware/cors";
export { errorHandler } from "./middleware/error-handler";
export { serveStatic } from "./middleware/static";
export { cookieParser, signCookie, unsignCookie } from "./middleware/cookie-parser";
export { compression } from "./middleware/compression";
export { helmet } from "./middleware/helmet";
export { rateLimit } from "./middleware/rate-limit";
export { csrf } from "./middleware/csrf";
export { session, MemoryStore, FileStore, fromExpressStore } from "./middleware/session";
export { logger } from "./middleware/logger";
export { upload, memoryStorage, diskStorage } from "./middleware/upload";
export { timeout } from "./middleware/timeout";
export { hpp } from "./middleware/hpp";
export { validate } from "./middleware/validation";
export { sse } from "./middleware/sse";
export { responseTime } from "./middleware/response-time";
export { requestId } from "./middleware/request-id";
export { methodOverride } from "./middleware/method-override";
export { favicon } from "./middleware/favicon";
export { jwt, jwtSign, jwtDecode } from "./middleware/jwt";
export { passport, passportInitialize, passportSession, passportAuthenticate } from "./middleware/passport";
export { tokenVault, VaultMemoryStore } from "./middleware/token-vault";
export type { VaultStore, VaultEntry, TokenVaultOptions, TokenPair, TokenVault } from "./middleware/token-vault";

export type { Handler, ErrorHandler, NextFunction, RouterOptions, ListenOptions, TlsOptions, CookieOptions, SendFileOptions } from "./types";
export type { RangeResult, RangeSpec } from "./core/request";
export type { BunWayOptions } from "./core/app";
export type { HttpErrorOptions } from "./core/errors";
export type { JsonOptions, UrlencodedOptions, TextOptions, RawOptions } from "./middleware/body-parser";
export type { CorsOptions } from "./middleware/cors";
export type { ErrorHandlerOptions } from "./middleware/error-handler";
export type { StaticOptions } from "./middleware/static";
export type { CookieParserOptions } from "./middleware/cookie-parser";
export type { CompressionOptions } from "./middleware/compression";
export type { HelmetOptions } from "./middleware/helmet";
export type { RateLimitOptions } from "./middleware/rate-limit";
export type { CsrfOptions } from "./middleware/csrf";
export type { SessionOptions, SessionStore, SessionData, Session, FileStoreOptions, LegacySessionStore } from "./middleware/session";
export type { LoggerOptions, FormatFn, TokenFn, RequestMeta, TokenRegistry } from "./middleware/logger";
export type { BunWayLogger, UploadedFile } from "./types";
export type { UploadOptions, UploadLimits, DiskStorageOptions, FieldSpec, StorageEngine, UploadInstance, UploadFactory } from "./middleware/upload";
export type { TimeoutOptions } from "./middleware/timeout";
export type { HppOptions } from "./middleware/hpp";
export type { ValidationSchema, ValidationOptions, ValidationError, FieldRule, ValidationSource } from "./middleware/validation";
export type { SseOptions } from "./middleware/sse";
export type { ResponseTimeOptions } from "./middleware/response-time";
export type { RequestIdOptions } from "./middleware/request-id";
export type { MethodOverrideOptions } from "./middleware/method-override";
export type { FaviconOptions } from "./middleware/favicon";
export type { JwtOptions, JwtPayload, JwtHeader, JwtAlgorithm } from "./middleware/jwt";
export type { AuthUser } from "./types";

// WebSocket types
export type { WebSocketData, WebSocketHandlers, WebSocketRouteDefinition, BunWebSocket } from "./types";

export { BUNWAY_DEFAULT_PORT } from "./types";
